/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Model.ChuongTrinhKhuyenMai;
import Model.Voucher;
import Service.QuanLyChuongTrinhService;
import Service.QuanLyVoucherService;
import com.toedter.calendar.JDateChooser;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 * @author Admin
 */
public class ViewKhuyenMai extends javax.swing.JPanel {

    private QuanLyVoucherService qlv = new QuanLyVoucherService();
    private DefaultTableModel dtmVoucher = new DefaultTableModel();
    private int indexchuongtrinh = -1;
    private QuanLyChuongTrinhService qlct = new QuanLyChuongTrinhService();
    private DefaultTableModel dtmChuongTrinh = new DefaultTableModel();
    private int indexvoucher = -1;
    private SimpleDateFormat t = new SimpleDateFormat("yyyy-MM-dd");
    private int currentPagechuongtrinh = 1;
    private int numberPagechuongtrinh;
    private int currentPagevoucher = 1;
    private int numberPagevoucher;
    private int limit = 5;
    private int i = -1;
    private int check;

    /**
     * Creates new form NewJPanel
     */
    public ViewKhuyenMai() {
        initComponents();
        this.fillTablechuongtrinh(currentPagechuongtrinh);
        this.fillTableVoucher(currentPagevoucher);
        tblBangChuongTrinh.setRowHeight(24);
        tblBangVoucher.setRowHeight(24);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMoTaChuongTrinh = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        txtTenChuongTrinh = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtMaChuongTrinh = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtGiamGiaChuongTrinh = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        rdoHoatDong = new javax.swing.JRadioButton();
        rdokhonghoatdong = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        btnThemCT = new javax.swing.JButton();
        btnSuaCT = new javax.swing.JButton();
        btnLamMoiCT = new javax.swing.JButton();
        lbliD = new javax.swing.JLabel();
        txtNgayBatDauChuongTrinh = new com.toedter.calendar.JDateChooser();
        txtNgayKetThucChuongTrinh = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBangChuongTrinh = new javax.swing.JTable();
        txttimkiem = new javax.swing.JTextField();
        btntimkiem = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        start = new javax.swing.JButton();
        btnprev = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        end = new javax.swing.JButton();
        lblnumberPage = new javax.swing.JLabel();
        rdohoatdong = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtMaVoucher = new javax.swing.JTextField();
        txtTenVoucher = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        txtDonToiThieu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtGiamToiDa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdohoatdong1 = new javax.swing.JRadioButton();
        rdokhonghoatdong1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSuaVoucher = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblIdVoucher = new javax.swing.JLabel();
        txtGiamGia = new javax.swing.JTextField();
        txtNgayBatDau = new com.toedter.calendar.JDateChooser();
        txtNgayKetThuc = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBangVoucher = new javax.swing.JTable();
        txttimkiemten = new javax.swing.JTextField();
        btntimkiemvc = new javax.swing.JButton();
        resetvcc = new javax.swing.JButton();
        start1 = new javax.swing.JButton();
        btnprev1 = new javax.swing.JButton();
        btnnext1 = new javax.swing.JButton();
        end1 = new javax.swing.JButton();
        lblpage1 = new javax.swing.JLabel();
        rdohoatdongbang = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1081, 700));

        jTabbedPane1.setBackground(new java.awt.Color(255, 251, 246));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1093, 750));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1091, 700));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Điền thông tin chương trình khuyến mãi"));

        txtMoTaChuongTrinh.setColumns(20);
        txtMoTaChuongTrinh.setRows(5);
        jScrollPane4.setViewportView(txtMoTaChuongTrinh);

        jLabel20.setText("Tên Chương Trình KM:");

        jLabel21.setText("Ngày Bắt Đầu:");

        jLabel22.setText("Id Chương Trình KM:");

        jLabel23.setText("Ngày Kết Thúc:");

        jLabel24.setText("Mã Chương Trình KM:");

        jLabel25.setText("Giảm Giá:");

        jLabel26.setText("Mô Tả:");

        jLabel27.setText("Trạng Thái:");

        buttonGroup2.add(rdoHoatDong);
        rdoHoatDong.setSelected(true);
        rdoHoatDong.setText("Hoạt Động");
        rdoHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoHoatDongActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdokhonghoatdong);
        rdokhonghoatdong.setText("Không hoạt động");
        rdokhonghoatdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdokhonghoatdongActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnThemCT.setBackground(new java.awt.Color(0, 102, 102));
        btnThemCT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemCT.setForeground(new java.awt.Color(255, 255, 255));
        btnThemCT.setText("Thêm");
        btnThemCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCTActionPerformed(evt);
            }
        });

        btnSuaCT.setBackground(new java.awt.Color(0, 102, 102));
        btnSuaCT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSuaCT.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaCT.setText("Sửa");
        btnSuaCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaCTActionPerformed(evt);
            }
        });

        btnLamMoiCT.setBackground(new java.awt.Color(0, 102, 102));
        btnLamMoiCT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLamMoiCT.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoiCT.setText("Làm mới");
        btnLamMoiCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiCTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLamMoiCT, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnThemCT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuaCT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLamMoiCT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        lbliD.setText("ID");

        txtNgayBatDauChuongTrinh.setDateFormatString("yyyy-MM-dd");

        txtNgayKetThucChuongTrinh.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(lbliD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 387, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNgayKetThucChuongTrinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGiamGiaChuongTrinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(txtNgayBatDauChuongTrinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdoHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdokhonghoatdong)
                        .addGap(105, 105, 105)))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTenChuongTrinh))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMaChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(79, 79, 79)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(519, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNgayBatDauChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbliD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNgayKetThucChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGiamGiaChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdokhonghoatdong)
                            .addComponent(rdoHoatDong))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(17, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel21))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(txtMaChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(txtTenChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25))
                    .addGap(20, 20, 20)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26)
                        .addComponent(jLabel27))
                    .addContainerGap()))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Khuyến Mãi"));

        tblBangChuongTrinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã chương trình KM", "Tên chương trình KM", "Mô tả", "Ngày bắt đầu", "Ngày kết thúc", "Giảm giá ", "Ngay tao", "Ngay sua", "Trạng thái"
            }
        ));
        tblBangChuongTrinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangChuongTrinhMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblBangChuongTrinh);

        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });

        btntimkiem.setBackground(new java.awt.Color(0, 102, 102));
        btntimkiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btntimkiem.setForeground(new java.awt.Color(255, 255, 255));
        btntimkiem.setText("Tìm Kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(0, 102, 102));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Làm Mới");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        start.setBackground(new java.awt.Color(0, 102, 102));
        start.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setText("|<");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        btnprev.setBackground(new java.awt.Color(0, 102, 102));
        btnprev.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnprev.setForeground(new java.awt.Color(255, 255, 255));
        btnprev.setText("<");
        btnprev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprevActionPerformed(evt);
            }
        });

        btnnext.setBackground(new java.awt.Color(0, 102, 102));
        btnnext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnnext.setForeground(new java.awt.Color(255, 255, 255));
        btnnext.setText(">");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        end.setBackground(new java.awt.Color(0, 102, 102));
        end.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        end.setForeground(new java.awt.Color(255, 255, 255));
        end.setText(">|");
        end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endActionPerformed(evt);
            }
        });

        lblnumberPage.setText("Số Trang");

        buttonGroup3.add(rdohoatdong);
        rdohoatdong.setSelected(true);
        rdohoatdong.setText("Hoạt Động");
        rdohoatdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdohoatdongActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton2);
        jRadioButton2.setText("Không Hoạt Động");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(start)
                .addGap(12, 12, 12)
                .addComponent(btnprev, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblnumberPage)
                .addGap(18, 18, 18)
                .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(end)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rdohoatdong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btntimkiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reset)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntimkiem)
                    .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txttimkiem)
                    .addComponent(rdohoatdong)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start)
                    .addComponent(btnprev)
                    .addComponent(btnnext)
                    .addComponent(end)
                    .addComponent(lblnumberPage)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chương trình khuyến mãi", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblId.setBackground(new java.awt.Color(255, 255, 255));
        lblId.setBorder(javax.swing.BorderFactory.createTitledBorder("Điền thông tin voucher"));

        jLabel10.setText("Mã Voucher:");

        jLabel4.setText("Mô tả:");

        jLabel7.setText("Đơn tối thiểu:");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane1.setViewportView(txtMoTa);

        txtDonToiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonToiThieuActionPerformed(evt);
            }
        });

        jLabel8.setText("Giảm tối đa:");

        jLabel5.setText("Ngày Bắt Đầu:");

        jLabel9.setText("Trạng Thái:");

        jLabel6.setText("Ngày Kết thúc:");

        buttonGroup1.add(rdohoatdong1);
        rdohoatdong1.setSelected(true);
        rdohoatdong1.setText("Hoạt Động");
        rdohoatdong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdohoatdong1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdokhonghoatdong1);
        rdokhonghoatdong1.setText("Không Hoạt Động");
        rdokhonghoatdong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdokhonghoatdong1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Id Voucher:");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnThem.setBackground(new java.awt.Color(0, 102, 102));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemjButton1ActionPerformed(evt);
            }
        });

        btnSuaVoucher.setBackground(new java.awt.Color(0, 102, 102));
        btnSuaVoucher.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSuaVoucher.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaVoucher.setText("Sửa");
        btnSuaVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaVoucherActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(0, 102, 102));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Lam moi");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoijButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuaVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel3.setText("Tên Voucher:");

        jLabel11.setText("Giam gia:");

        lblIdVoucher.setText("ID");

        txtNgayBatDau.setDateFormatString("yyyy-MM-dd");

        txtNgayKetThuc.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout lblIdLayout = new javax.swing.GroupLayout(lblId);
        lblId.setLayout(lblIdLayout);
        lblIdLayout.setHorizontalGroup(
            lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblIdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtMaVoucher, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenVoucher)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(lblIdVoucher, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGiamGia, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(107, 107, 107)
                .addGroup(lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lblIdLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdohoatdong1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdokhonghoatdong1))
                    .addGroup(lblIdLayout.createSequentialGroup()
                        .addGroup(lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDonToiThieu, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(txtGiamToiDa, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(txtNgayBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(75, 75, 75)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        lblIdLayout.setVerticalGroup(
            lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblIdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lblIdLayout.createSequentialGroup()
                        .addGroup(lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblIdVoucher)
                                .addComponent(jLabel2))
                            .addComponent(txtNgayBatDau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblIdLayout.createSequentialGroup()
                                .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addGroup(lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDonToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtGiamToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(lblIdLayout.createSequentialGroup()
                                .addGroup(lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMaVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rdohoatdong1)
                                .addComponent(jLabel9)
                                .addComponent(rdokhonghoatdong1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(lblIdLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addGap(18, 18, 18))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Voucher"));

        tblBangVoucher.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblBangVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Ma Voucher", "Tên Voucher", "Mô tả", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Giảm Giá", "Giảm Tối đa", "Đơn Tối Thiểu", "Ngay Them", "Ngay Sua", "Trạng Thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblBangVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangVoucherMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBangVoucher);

        txttimkiemten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemtenActionPerformed(evt);
            }
        });

        btntimkiemvc.setBackground(new java.awt.Color(0, 102, 102));
        btntimkiemvc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btntimkiemvc.setForeground(new java.awt.Color(255, 255, 255));
        btntimkiemvc.setText("Tìm Kiếm");
        btntimkiemvc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemvcActionPerformed(evt);
            }
        });

        resetvcc.setBackground(new java.awt.Color(0, 102, 102));
        resetvcc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resetvcc.setForeground(new java.awt.Color(255, 255, 255));
        resetvcc.setText("Làm Mới");
        resetvcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetvccActionPerformed(evt);
            }
        });

        start1.setBackground(new java.awt.Color(0, 102, 102));
        start1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        start1.setForeground(new java.awt.Color(255, 255, 255));
        start1.setText("|<");
        start1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start1ActionPerformed(evt);
            }
        });

        btnprev1.setBackground(new java.awt.Color(0, 102, 102));
        btnprev1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnprev1.setForeground(new java.awt.Color(255, 255, 255));
        btnprev1.setText("<");
        btnprev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprev1ActionPerformed(evt);
            }
        });

        btnnext1.setBackground(new java.awt.Color(0, 102, 102));
        btnnext1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnnext1.setForeground(new java.awt.Color(255, 255, 255));
        btnnext1.setText(">");
        btnnext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnext1ActionPerformed(evt);
            }
        });

        end1.setBackground(new java.awt.Color(0, 102, 102));
        end1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        end1.setForeground(new java.awt.Color(255, 255, 255));
        end1.setText(">|");
        end1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end1ActionPerformed(evt);
            }
        });

        lblpage1.setText("page");

        buttonGroup5.add(rdohoatdongbang);
        rdohoatdongbang.setSelected(true);
        rdohoatdongbang.setText("Hoạt Động");
        rdohoatdongbang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdohoatdongbangActionPerformed(evt);
            }
        });

        buttonGroup5.add(jRadioButton4);
        jRadioButton4.setText("Không Hoạt Động");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdohoatdongbang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txttimkiemten, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntimkiemvc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetvcc)
                .addGap(34, 34, 34))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(start1)
                .addGap(18, 18, 18)
                .addComponent(btnprev1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblpage1)
                .addGap(15, 15, 15)
                .addComponent(btnnext1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(end1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimkiemten, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntimkiemvc)
                    .addComponent(resetvcc)
                    .addComponent(rdohoatdongbang)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start1)
                    .addComponent(btnprev1)
                    .addComponent(btnnext1)
                    .addComponent(lblpage1)
                    .addComponent(end1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        jTabbedPane1.addTab("Voucher", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDonToiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonToiThieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonToiThieuActionPerformed

    private void LocTrangThaiVoucher(int trangThai) {
        List<Voucher> VoucherList = qlv.LocTrangThai(trangThai);
        dtmVoucher.setRowCount(0);
        for (Voucher voucher : VoucherList) {
            dtmVoucher.addRow(voucher.toDataRow());
        }
    }

    private void rdohoatdong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdohoatdong1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rdohoatdong1ActionPerformed

    private void rdokhonghoatdong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdokhonghoatdong1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rdokhonghoatdong1ActionPerformed
    private Date NhapNgayThuCong(JDateChooser dateChooser) {
        Date date = dateChooser.getDate();
        if (date != null) {
            return date;
        }
        String NhapNgay = ((JTextField) dateChooser.getDateEditor().getUiComponent()).getText();
        if (!NhapNgay.trim().isEmpty()) {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                sdf.setLenient(false);
                return sdf.parse(NhapNgay);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, "Định dạng ngày không hợp lệ: " + NhapNgay);
            }
        }
        return null;
    }
    private void btnThemjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemjButton1ActionPerformed
        if (validateVoucher()) {
            if (qlv.checkTrungMa(txtMaVoucher.getText())) {
                JOptionPane.showMessageDialog(this, "Mã voucher đã tồn tại! Vui lòng chọn mã khác.");
                txtMaVoucher.requestFocus();
                return;
            }
            int option = JOptionPane.showConfirmDialog(this,
                    "Bạn có chắc chắn muốn thêm Voucher này?",
                    "Xác nhận",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (option == JOptionPane.YES_OPTION) {
                Voucher newVoucher = readFormvoucherngaytao();
                qlv.addVoucher(newVoucher);
                JOptionPane.showMessageDialog(this, "Voucher đã được thêm thành công.");
                clearVoucher();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm Voucher đã bị hủy.");
            }
        }
    }//GEN-LAST:event_btnThemjButton1ActionPerformed

    private boolean validateVoucher() {
        if (txtMaVoucher.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã Voucher.");
            txtMaVoucher.requestFocus();
            return false;
        }
        if (txtTenVoucher.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Tên Voucher.");
            txtTenVoucher.requestFocus();
            return false;
        }
        if (txtMoTa.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mô Tả Voucher.");
            txtMoTa.requestFocus();
            return false;
        }
        if (txtDonToiThieu.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đơn tối thiểu.");
            txtDonToiThieu.requestFocus();
            return false;
        }
        if (txtDonToiThieu.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đơn tối thiểu.");
            txtDonToiThieu.requestFocus();
            return false;
        }
        if (txtGiamToiDa.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giảm tối đa.");
            txtGiamToiDa.requestFocus();
            return false;
        }
        if (txtGiamGia.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giảm giá.");
            txtGiamGia.requestFocus();
            return false;
        }
        Date ngayBatDau = txtNgayBatDau.getDate();
        Date ngayKetThuc = txtNgayKetThuc.getDate();
        Date ngayHienTai = new Date(); // Ngày hiện tại

        if (ngayBatDau == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Ngày Bắt Đầu.");
            txtNgayBatDau.requestFocus();
            return false;
        }

        if (ngayKetThuc == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Ngày Kết Thúc.");
            txtNgayKetThuc.requestFocus();
            return false;
        }
        if (!ngayKetThuc.after(ngayHienTai)) {
            JOptionPane.showMessageDialog(this, "Ngày Kết Thúc phải lớn hơn ngày hiện tại.");
            txtNgayKetThuc.requestFocus();
            return false;
        }
        if (!ngayBatDau.before(ngayKetThuc)) {
            JOptionPane.showMessageDialog(this, "Ngày Bắt Đầu phải trước Ngày Kết Thúc.");
            txtNgayBatDau.requestFocus();
            return false;
        }
        int discount;
        try {
            discount = Integer.parseInt(txtGiamGia.getText().trim());
            if (discount < 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Giảm Giá hợp lệ .");
                txtGiamGia.requestFocus();
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Giảm Giá hợp lệ (số nguyên).");
            txtGiamGia.requestFocus();
            return false;
        }
        int giaTD;
        try {
            giaTD = Integer.parseInt(txtGiamToiDa.getText().trim());
            if (giaTD < 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Giảm tối đa hợp lệ .");
                txtGiamToiDa.requestFocus();
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Giảm tối đa hợp lệ (số nguyên).");
            txtGiamToiDa.requestFocus();
            return false;
        }
        int donTT;
        try {
            donTT = Integer.parseInt(txtDonToiThieu.getText().trim());
            if (donTT <= 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đơn tối thiểu hợp lệ (lớn hơn 0).");
                txtDonToiThieu.requestFocus();
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đơn tối thiểu hợp lệ (số nguyên).");
            txtDonToiThieu.requestFocus();
            return false;
        }
        return true;
    }

    private void rdokhonghoatdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdokhonghoatdongActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rdokhonghoatdongActionPerformed

    private void LocTrangThaiChuongTrinh(int trangThai) {
        List<ChuongTrinhKhuyenMai> chuongTrinhList = qlct.LocTrangThai(trangThai);
        dtmChuongTrinh.setRowCount(0);
        for (ChuongTrinhKhuyenMai chuongTrinh : chuongTrinhList) {
            dtmChuongTrinh.addRow(chuongTrinh.toDataRow());
        }
    }
    private void btnThemCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCTActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm chương trình khuyến mãi này không?",
                "Xác nhận thêm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            if (qlct.checkTrungMa(txtMaChuongTrinh.getText())) {
                JOptionPane.showMessageDialog(this, "Mã chương trình khuyến mãi đã tồn tại! Vui lòng chọn mã khác.");
                txtMaChuongTrinh.requestFocus();
                return;
            }
            if (validatectkm()) {
                ChuongTrinhKhuyenMai newChuongTrinh = readFormChuongTrinhNgayTao();
                int isAdded = qlct.addChuongTrinh(newChuongTrinh);
                if (isAdded > 0) {
                    JOptionPane.showMessageDialog(this, "Chương trình khuyến mãi đã được thêm thành công!");
                    fillTablechuongtrinh(currentPagechuongtrinh);  
                    clearct();
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi khi thêm chương trình khuyến mãi. Vui lòng thử lại!");
                }
            }
        }
    }//GEN-LAST:event_btnThemCTActionPerformed

    private boolean validatectkm() {
        if (txtMaChuongTrinh.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã Chương Trình.");
            txtMaChuongTrinh.requestFocus();
            return false;
        }
        if (txtTenChuongTrinh.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Tên Chương Trình.");
            txtTenChuongTrinh.requestFocus();
            return false;
        }
        if (txtMoTaChuongTrinh.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mô Tả Chương Trình.");
            txtMoTaChuongTrinh.requestFocus();
            return false;
        }
        Date ngayBatDau = txtNgayBatDauChuongTrinh.getDate();
        Date ngayKetThuc = txtNgayKetThucChuongTrinh.getDate();
        Date ngayHienTai = new Date(); // Ngày hiện tại

        if (ngayBatDau == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Ngày Bắt Đầu.");
            txtNgayBatDauChuongTrinh.requestFocus();
            return false;
        }
        if (ngayKetThuc == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Ngày Kết Thúc.");
            txtNgayKetThucChuongTrinh.requestFocus();
            return false;
        }
        if (!ngayKetThuc.after(ngayHienTai)) {
            JOptionPane.showMessageDialog(this, "Ngày Kết Thúc phải lớn hơn ngày hiện tại.");
            txtNgayKetThucChuongTrinh.requestFocus();
            return false;
        }

        if (!ngayBatDau.before(ngayKetThuc)) {
            JOptionPane.showMessageDialog(this, "Ngày Bắt Đầu phải trước Ngày Kết Thúc.");
            txtNgayBatDauChuongTrinh.requestFocus();
            return false;
        }
        int discount;
        try {
            discount = Integer.parseInt(txtGiamGiaChuongTrinh.getText().trim());
            if (discount < 0) {
                JOptionPane.showMessageDialog(this, "Giảm giá không được là số âm.");
                txtGiamGiaChuongTrinh.requestFocus();
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Giảm Giá hợp lệ (số nguyên).");
            txtGiamGiaChuongTrinh.requestFocus();
            return false;
        }

        return true;
    }

    private void tblBangVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangVoucherMouseClicked
        indexvoucher = tblBangVoucher.getSelectedRow();
        fillFormVoucher(indexvoucher);
        txtMaVoucher.setEditable(false);
    }//GEN-LAST:event_tblBangVoucherMouseClicked

    private void btnLamMoijButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoijButton3ActionPerformed
        clearVoucher();
        txtMaVoucher.setEditable(true);
    }//GEN-LAST:event_btnLamMoijButton3ActionPerformed

    private void btnSuaVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaVoucherActionPerformed
        // Kiểm tra xem có chọn được voucher trong bảng không
        if (indexvoucher >= 0) {
            if (!validateVoucher()) {
                return;
            }
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa voucher này không?",
                    "Xác nhận sửa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (chon == JOptionPane.YES_OPTION) {
                int voucherId = (int) tblBangVoucher.getValueAt(indexvoucher, 0);
                int isUpdated = qlv.updateVoucher(readFormvoucherngaysua(), voucherId);
                if (isUpdated > 0) {
                    fillTableVoucher(currentPagevoucher);
                    JOptionPane.showMessageDialog(this, "Sửa voucher thành công.");
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật voucher thất bại. Vui lòng thử lại.");
                }
                clearVoucher();
                indexvoucher = -1;
            } else {
                JOptionPane.showMessageDialog(this, "Sửa voucher bị hủy.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hãy chọn voucher muốn sửa.");
        }
    }//GEN-LAST:event_btnSuaVoucherActionPerformed

    private void tblBangChuongTrinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangChuongTrinhMouseClicked
        indexchuongtrinh = tblBangChuongTrinh.getSelectedRow();
        fillFormChuongTrinh(indexchuongtrinh);
        txtMaChuongTrinh.setEditable(false);
    }//GEN-LAST:event_tblBangChuongTrinhMouseClicked

    private void btnLamMoiCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiCTActionPerformed
        clearct();
        txtMaChuongTrinh.setEditable(true);
    }//GEN-LAST:event_btnLamMoiCTActionPerformed

    private void btnSuaCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaCTActionPerformed
        if (indexchuongtrinh >= 0) {
            if (!validatectkm()) {
                return;
            }
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa chương trình này không?",
                    "Xác nhận sửa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (chon == JOptionPane.YES_OPTION) {
                try {
                    ChuongTrinhKhuyenMai ct = readFormChuongTrinhngaySua();
                    if (ct == null) {
                        return;
                    }
                   
                    
                    Integer id = Integer.valueOf(lbliD.getText());
                    qlct.updateChuongTrinh(readFormChuongTrinhngaySua(),id);
                    this.fillTablechuongtrinh(currentPagechuongtrinh);
                    JOptionPane.showMessageDialog(this, "Sửa dữ liệu thành công!");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Sửa chương trình bị hủy.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hãy chọn chương trình muốn sửa.");
        }
    }//GEN-LAST:event_btnSuaCTActionPerformed

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txttimkiemActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        int totalPages = qlct.TongSoTrangChuongTrinh();
        if (currentPagechuongtrinh < totalPages) {
            currentPagechuongtrinh++;
            fillTablechuongtrinh(currentPagechuongtrinh);
            lblnumberPage.setText("" + currentPagechuongtrinh);
        }
    }//GEN-LAST:event_btnnextActionPerformed

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:
        String tenSanPham = txttimkiem.getText().trim();
        if (tenSanPham.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên sản phẩm để tìm kiếm.");
            return;
        }
        List<ChuongTrinhKhuyenMai> result = qlct.searchByTenChuongTrinh(tenSanPham);
        if (result.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm với tên: " + tenSanPham);
        } else {
            DefaultTableModel model = (DefaultTableModel) tblBangChuongTrinh.getModel();
            model.setRowCount(0);
            for (ChuongTrinhKhuyenMai ct : result) {
                model.addRow(new Object[]{
                    ct.getId(),
                    ct.getMaChuongTrinh(),
                    ct.getTenChuongTrinh(),
                    ct.getMoTaChuongTrinh(),
                    ct.getNgayBatDauChuongTrinh(),
                    ct.getNgayKetThucChuongTrinh(),
                    ct.getGiamGiaChuongTrinh(),
                    ct.getNgayTaoChuongTrinh(),
                    ct.getNgaySuaChuongTrinh(),
                    ct.getTrangThaiChuongTrinh() == 1 ? "Hoat dong" : "Dung hoat dong"
                });
            }
        }
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void btnprevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprevActionPerformed

        if (currentPagechuongtrinh > 1) {
            currentPagechuongtrinh--;
            fillTablechuongtrinh(currentPagechuongtrinh);
            lblnumberPage.setText("" + currentPagechuongtrinh);
        }
    }//GEN-LAST:event_btnprevActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        currentPagechuongtrinh = 1;
        fillTablechuongtrinh(currentPagechuongtrinh);
        lblnumberPage.setText("" + currentPagechuongtrinh);
    }//GEN-LAST:event_startActionPerformed

    private void endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endActionPerformed
        // TODO add your handling code here:
        int totalPages = qlct.TongSoTrangChuongTrinh();
        currentPagechuongtrinh = totalPages;
        fillTablechuongtrinh(currentPagechuongtrinh);
        lblnumberPage.setText("" + currentPagechuongtrinh);
    }//GEN-LAST:event_endActionPerformed

    private void rdoHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoHoatDongActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rdoHoatDongActionPerformed

    private void start1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start1ActionPerformed
        // TODO add your handling code here:
        currentPagevoucher = 1;
        fillTableVoucher(currentPagevoucher);
        lblpage1.setText("" + currentPagevoucher);
    }//GEN-LAST:event_start1ActionPerformed

    private void btnprev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprev1ActionPerformed
        // TODO add your handling code here:
        if (currentPagevoucher > 1) {
            currentPagevoucher--;
            fillTableVoucher(currentPagevoucher);
            lblpage1.setText("" + currentPagevoucher);
        }
    }//GEN-LAST:event_btnprev1ActionPerformed

    private void btnnext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnext1ActionPerformed
        // TODO add your handling code here:
        int totalPages = qlv.getTongSoTrang();
        if (currentPagevoucher < totalPages) {
            currentPagevoucher++;
            fillTableVoucher(currentPagevoucher);
            lblpage1.setText("" + currentPagevoucher);
        }
    }//GEN-LAST:event_btnnext1ActionPerformed

    private void end1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end1ActionPerformed
        // TODO add your handling code here:
        int totalPages = qlv.getTongSoTrang();
        currentPagevoucher = totalPages;
        fillTableVoucher(currentPagevoucher);
        lblpage1.setText("" + currentPagevoucher);
    }//GEN-LAST:event_end1ActionPerformed

    private void btntimkiemvcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemvcActionPerformed
        String tenVoucher = txttimkiemten.getText().trim();
        if (tenVoucher.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên voucher để tìm kiếm.");
            return;
        }
        List<Voucher> result = qlv.searchVoucherByName(tenVoucher);
        if (result.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy voucher với tên: " + tenVoucher);
        } else {
            DefaultTableModel model = (DefaultTableModel) tblBangVoucher.getModel();
            model.setRowCount(0);
            for (Voucher v : result) {
                model.addRow(new Object[]{
                    v.getId(),
                    v.getMaVoucher(),
                    v.getTenVocher(),
                    v.getMoTa(),
                    v.getNgayBatDau(),
                    v.getNgayKetThuc(),
                    v.getGiamGia(),
                    v.getGiamToiDa(),
                    v.getDonToiThieu(),
                    v.getNgayTao(),
                    v.getNgaySua(),
                    v.getTrangThai() == 1 ? "Hoạt động" : "Dừng hoạt động"
                });
            }
        }
    }//GEN-LAST:event_btntimkiemvcActionPerformed

    private void txttimkiemtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemtenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimkiemtenActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        fillTablechuongtrinh(currentPagechuongtrinh);
        rdohoatdong.setSelected(true);
    }//GEN-LAST:event_resetActionPerformed

    private void resetvccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetvccActionPerformed
        // TODO add your handling code here:
        fillTableVoucher(currentPagevoucher);
        rdohoatdongbang.setSelected(true);
    }//GEN-LAST:event_resetvccActionPerformed

    private void rdohoatdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdohoatdongActionPerformed
        // TODO add your handling code here:
        LocTrangThaiChuongTrinh(1);
    }//GEN-LAST:event_rdohoatdongActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        LocTrangThaiChuongTrinh(0);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void rdohoatdongbangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdohoatdongbangActionPerformed
        // TODO add your handling code here:
        LocTrangThaiVoucher(1);
    }//GEN-LAST:event_rdohoatdongbangActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        LocTrangThaiVoucher(0);
    }//GEN-LAST:event_jRadioButton4ActionPerformed
    // <editor-fold defaultstate="collapsed" desc="Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLamMoiCT;
    private javax.swing.JButton btnSuaCT;
    private javax.swing.JButton btnSuaVoucher;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemCT;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnnext1;
    private javax.swing.JButton btnprev;
    private javax.swing.JButton btnprev1;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btntimkiemvc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton end;
    private javax.swing.JButton end1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel lblId;
    private javax.swing.JLabel lblIdVoucher;
    private javax.swing.JLabel lbliD;
    private javax.swing.JLabel lblnumberPage;
    private javax.swing.JLabel lblpage1;
    private javax.swing.JRadioButton rdoHoatDong;
    private javax.swing.JRadioButton rdohoatdong;
    private javax.swing.JRadioButton rdohoatdong1;
    private javax.swing.JRadioButton rdohoatdongbang;
    private javax.swing.JRadioButton rdokhonghoatdong;
    private javax.swing.JRadioButton rdokhonghoatdong1;
    private javax.swing.JButton reset;
    private javax.swing.JButton resetvcc;
    private javax.swing.JButton start;
    private javax.swing.JButton start1;
    private javax.swing.JTable tblBangChuongTrinh;
    private javax.swing.JTable tblBangVoucher;
    private javax.swing.JTextField txtDonToiThieu;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtGiamGiaChuongTrinh;
    private javax.swing.JTextField txtGiamToiDa;
    private javax.swing.JTextField txtMaChuongTrinh;
    private javax.swing.JTextField txtMaVoucher;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextArea txtMoTaChuongTrinh;
    private com.toedter.calendar.JDateChooser txtNgayBatDau;
    private com.toedter.calendar.JDateChooser txtNgayBatDauChuongTrinh;
    private com.toedter.calendar.JDateChooser txtNgayKetThuc;
    private com.toedter.calendar.JDateChooser txtNgayKetThucChuongTrinh;
    private javax.swing.JTextField txtTenChuongTrinh;
    private javax.swing.JTextField txtTenVoucher;
    private javax.swing.JTextField txttimkiem;
    private javax.swing.JTextField txttimkiemten;
    // End of variables declaration//GEN-END:variables
// </editor-fold>
    private void fillTableVoucher(int page) {
        List<Voucher> list = qlv.getAllVoucher(page);
        this.getPageVoucher(list);
        dtmVoucher = (DefaultTableModel) tblBangVoucher.getModel();
        dtmVoucher.setRowCount(0);
        for (Voucher voucher : list) {
            dtmVoucher.addRow(voucher.toDataRow());
        }
    }

    void getPageVoucher(List<Voucher> list1) {
        if (list1.size() % limit == 0) {
            numberPagevoucher = list1.size() / limit;
        } else {
            numberPagevoucher = (list1.size() / limit) + 1;
        }
        lblnumberPage.setText("1");
    }

    private void fillFormVoucher(int index) {
        lblIdVoucher.setText((tblBangVoucher.getValueAt(index, 0)).toString());
        txtMaVoucher.setText(tblBangVoucher.getValueAt(index, 1).toString());
        txtTenVoucher.setText(tblBangVoucher.getValueAt(index, 2).toString());
        txtMoTa.setText(tblBangVoucher.getValueAt(index, 3).toString());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String ngayBatDauStr = tblBangVoucher.getValueAt(index, 4).toString();
        String ngayKetThucStr = tblBangVoucher.getValueAt(index, 5).toString();
        try {
            Date ngayBatDau = sdf.parse(ngayBatDauStr);
            Date ngayKetThuc = sdf.parse(ngayKetThucStr);
            txtNgayBatDau.setDate(ngayBatDau);
            txtNgayKetThuc.setDate(ngayKetThuc);
        } catch (ParseException ex) {
            Logger.getLogger(ViewKhuyenMai.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Định dạng ngày không hợp lệ: " + ex.getMessage());
        }
        txtGiamGia.setText(tblBangVoucher.getValueAt(index, 6).toString());
        txtGiamToiDa.setText(tblBangVoucher.getValueAt(index, 7).toString());
        txtDonToiThieu.setText(tblBangVoucher.getValueAt(index, 8).toString());
        if (tblBangVoucher.getValueAt(index, 11).toString().equals("Hoat dong")) {
            rdohoatdong1.setSelected(true);
        } else {
            rdokhonghoatdong1.setSelected(true);
        }
    }

    private Voucher readFormvoucherngaytao() {
        int a;
        LocalDateTime ldt = LocalDateTime.now();
        Date ngayTao = java.sql.Timestamp.valueOf(ldt);
        Date ngayBatDau = txtNgayBatDau.getDate();
        Date ngayKetThuc = txtNgayKetThuc.getDate();
        ngayBatDau = NhapNgayThuCong(txtNgayBatDau);
        ngayKetThuc = NhapNgayThuCong(txtNgayKetThuc);
        if (rdohoatdong1.isSelected()) {
            a = 1;
        } else {
            a = 0;
        }
        return new Voucher(txtMaVoucher.getText(), txtTenVoucher.getText(), txtMoTa.getText(), ngayBatDau, ngayKetThuc, Integer.valueOf(txtGiamGia.getText()), Integer.valueOf(txtGiamToiDa.getText()), Integer.valueOf(txtDonToiThieu.getText()), ngayTao, a);
    }

    private Voucher readFormvoucherngaysua() {
        int a;
        LocalDateTime ldt = LocalDateTime.now();
        Date ngaySua = java.sql.Timestamp.valueOf(ldt);
        Date ngayBatDau = txtNgayBatDau.getDate();
        Date ngayKetThuc = txtNgayKetThuc.getDate();
        ngayBatDau = NhapNgayThuCong(txtNgayBatDau);
        ngayKetThuc = NhapNgayThuCong(txtNgayKetThuc);
        if (rdohoatdong1.isSelected()) {
            a = 1;
        } else {
            a = 0;
        }
        return new Voucher(txtMaVoucher.getText(), txtTenVoucher.getText(), txtMoTa.getText(), ngayBatDau, ngayKetThuc, Integer.valueOf(txtGiamGia.getText()), Integer.valueOf(txtGiamToiDa.getText()), Integer.valueOf(txtDonToiThieu.getText()), a, ngaySua);
    }

    private void clearVoucher() {
        lblIdVoucher.setText("ID");
        txtMaVoucher.setText("");
        txtTenVoucher.setText("");
        txtMoTa.setText("");
        txtNgayBatDau.setDate(null);
        txtNgayKetThuc.setDate(null);
        txtGiamGia.setText("");
        txtGiamToiDa.setText("");
        txtDonToiThieu.setText("");
        rdohoatdong1.setSelected(true);
        indexvoucher = -1;
    }

    void getPageChuongTrinh(List<ChuongTrinhKhuyenMai> list) {
        if (list.size() % limit == 0) {
            numberPagechuongtrinh = list.size() / limit;
        } else {
            numberPagechuongtrinh = (list.size() / limit) + 1;
        }
        lblpage1.setText("1");
    }

    void fillTablechuongtrinh(int page) {
        List<ChuongTrinhKhuyenMai> list = qlct.getAllChuongTrinh(page);
        this.getPageChuongTrinh(list);
        dtmChuongTrinh = (DefaultTableModel) tblBangChuongTrinh.getModel();
        dtmChuongTrinh.setRowCount(0);
        for (ChuongTrinhKhuyenMai chuongTrinh : list) {
            dtmChuongTrinh.addRow(chuongTrinh.toDataRow());
        }
    }

    private void fillFormChuongTrinh(int index) {
        lbliD.setText(tblBangChuongTrinh.getValueAt(index, 0).toString());
        txtMaChuongTrinh.setText(tblBangChuongTrinh.getValueAt(index, 1).toString());
        txtTenChuongTrinh.setText(tblBangChuongTrinh.getValueAt(index, 2).toString());
        txtMoTaChuongTrinh.setText(tblBangChuongTrinh.getValueAt(index, 3).toString());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            String ngayBatDauStr = tblBangChuongTrinh.getValueAt(index, 4).toString();
            String ngayKetThucStr = tblBangChuongTrinh.getValueAt(index, 5).toString();
            Date ngayBatDau = sdf.parse(ngayBatDauStr);
            Date ngayKetThuc = sdf.parse(ngayKetThucStr);
            txtNgayBatDauChuongTrinh.setDate(ngayBatDau);
            txtNgayKetThucChuongTrinh.setDate(ngayKetThuc);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Định dạng ngày không hợp lệ: " + ex.getMessage());
        }
        txtGiamGiaChuongTrinh.setText(tblBangChuongTrinh.getValueAt(index, 6).toString());
        if ("Hoat dong".equalsIgnoreCase(tblBangChuongTrinh.getValueAt(index, 9).toString())) {
            rdoHoatDong.setSelected(true);
        } else {
            rdokhonghoatdong.setSelected(true);
        }
    }

    private ChuongTrinhKhuyenMai readFormChuongTrinhNgayTao() {
        int a;
        LocalDateTime ldt = LocalDateTime.now();
        Date ngayTao = java.sql.Timestamp.valueOf(ldt);
        Date ngayBatDau = txtNgayBatDauChuongTrinh.getDate();
        Date ngayKetThuc = txtNgayKetThucChuongTrinh.getDate();
        ngayBatDau = NhapNgayThuCong(txtNgayBatDauChuongTrinh);
        ngayKetThuc = NhapNgayThuCong(txtNgayKetThucChuongTrinh);
        if (rdoHoatDong.isSelected()) {
            a = 1;
        } else {
            a = 0;
        }
        return new ChuongTrinhKhuyenMai(
                txtMaChuongTrinh.getText(),
                txtTenChuongTrinh.getText(),
                txtMoTaChuongTrinh.getText(),
                ngayBatDau,
                ngayKetThuc,
                Integer.valueOf(txtGiamGiaChuongTrinh.getText().trim()), // Loại bỏ khoảng trắng nếu có
                ngayTao,
                a
        );
    }

    private ChuongTrinhKhuyenMai readFormChuongTrinhngaySua() {
        int a;
        LocalDateTime ldt = LocalDateTime.now();
        Date ngaySua = java.sql.Timestamp.valueOf(ldt);
        Date ngayBatDau = txtNgayBatDauChuongTrinh.getDate();
        Date ngayKetThuc = txtNgayKetThucChuongTrinh.getDate();
        ngayBatDau = NhapNgayThuCong(txtNgayBatDauChuongTrinh);
        ngayKetThuc = NhapNgayThuCong(txtNgayKetThucChuongTrinh);
        if (rdoHoatDong.isSelected()) {
            a = 1;
        } else {
            a = 0;
        }
        return new ChuongTrinhKhuyenMai(txtMaChuongTrinh.getText(), txtTenChuongTrinh.getText(), txtMoTaChuongTrinh.getText(), ngayBatDau, ngayKetThuc, Integer.valueOf(txtGiamGiaChuongTrinh.getText()), a, ngaySua);
    }

    private void clearct() {
        lbliD.setText("ID");
        txtMaChuongTrinh.setText("");
        txtTenChuongTrinh.setText("");
        txtMoTaChuongTrinh.setText("");
        txtNgayBatDauChuongTrinh.setDate(null);
        txtNgayKetThucChuongTrinh.setDate(null);
        txtGiamGiaChuongTrinh.setText("");
        rdoHoatDong.setSelected(true);
        indexchuongtrinh = -1;
    }
}
